{% set name = "numbagg" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numbagg-{{ version }}.tar.gz
  sha256: 45ba41077b7a621e35eaa4c294d90b22e75e8513b8c211f59d2b9be840fc1175

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba

test:
  imports:
    - numbagg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/numbagg/numbagg
  summary: Fast N-dimensional aggregation functions with Numba
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - max-sixty
    - dcherian
    - ocefpaf
