{% set name = "numbagg" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numbagg-{{ version }}.tar.gz
  sha256: 08298bb1fb8e55816d1a677c36595e4b4bb5695f9e513f684a97bdabf4f129bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy
    - numba

test:
  imports:
    - numbagg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/numbagg/numbagg
  summary: Fast N-dimensional aggregation functions with Numba
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
