{% set name = "numbagg" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numbagg-{{ version }}.tar.gz
  sha256: 7c3107d9fa10de999d17640bedb835669005008b16eb0aa308d6854b1ce49d2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba

test:
  imports:
    - numbagg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/numbagg/numbagg
  summary: Fast N-dimensional aggregation functions with Numba
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - max-sixty
    - dcherian
    - ocefpaf
