{% set name = "numbagg" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numbagg-{{ version }}.tar.gz
  sha256: 3a111361e6062feafd600b1e3c8a8187fd55e955bee735ada843705395fe84d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - numpy
    - numba

test:
  imports:
    - numbagg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/numbagg/numbagg
  summary: Fast N-dimensional aggregation functions with Numba
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - max-sixty
    - dcherian
    - ocefpaf
